### ISSUE TITLE
Using preview is not possible if you have very long filenames

### ISSUE THREAD

**Issue by oderwat** [antonmedv/walk#151]
I was in a directory with very long filenames (longer than the terminal width) and switched on preview mode. It seems this is not working. I guess the filenames need to be shortened in some way (and or make the left side scrollable horizontally).

**Comment by antonmedv** [comment]
Fixed! I found the bug.

**Comment by Suall1969** [comment]
This issue still persists in Terminal.app as of v1.13.0. Besides, after scrolling up one row, everything shifts up one row which swaps the entry immediately after the cursor.

https://github.com/user-attachments/assets/94d1790d-5766-4bf5-a72e-402c266cd07b
